---
plant_name: Example Plant
groups:
- cam_params_dir: calibration/camera_8hz/parameters
  ir_or_rgb: ir
  clusters:
  - cluster_idx: 0
    frame_idx_start: 0
    frame_idx_end: 2541
  settings:
    prepare_opensfm:
      select_frames_mode: gps_visual
    opensfm:
      matching_gps_distance: 100
      align_method: orientation_prior
      align_orientation_prior: vertical
      robust_matching_min_match: 8 

tasks:
  - track_pv_modules
  - compute_pv_module_quadrilaterals
  # - prepare_opensfm
  # - opensfm_extract_metadata
  # - opensfm_detect_features
  #  - opensfm_match_features
  #  - opensfm_create_tracks
  #  - opensfm_reconstruct
  #  - triangulate_pv_modules
  #  - refine_triangulation
  #  - crop_pv_modules